.github/ISSUE_TEMPLATE/bug.yml
.github/ISSUE_TEMPLATE/feature.yml
.github/ISSUE_TEMPLATE/help.yml

**이슈 템플릿 제목 수정**
이슈 템플릿 제목 수정
이슈 템플릿 제목 수정

[docs] 이슈 템플릿 제목 수정

---

.eslintrc.cjs

**eslint 문서 수정**
eslint 문서 수정
eslint 문서 수정

[docs] eslint 문서 수정

---

.prettierrc

** prettier 문서 수정**
prettier 문서 수정을 진행했습니다.
기존 설치하면 생긴 prettier 문서에서 커스텀화 prettier 문서으로 수정했습니다.

[docs] prettier 문서 수정

---

.eslintrc.cjs
.husky/pre-commit
package-lock.json
package.json
src/App.tsx
src/main.tsx
tsconfig.app.json
vite.config.ts

npm run lint 하면 CLI에 나오는 에러들 전부 해결완료 ( 타스 버전, 중복 오류였음 )
npm run lint ( 정상 작동 )
허스키 테스트 ( 정상 작동 ) 
이모션 테스트 ( 정상 작동 )
프리티어 ( 웹스톰에서는 정상작동 )
전부 고치고 세팅 했습니다 
타스 버전 고정, 다운그레이드, 린트 코드 수정 ( 안쓰는거 off 함 )
이거 클론하고 나서 적용할때 혹시나 문제생기면 연락주세요 
허스키는 
`const foo = 1
console.log(foo)`
이렇게 테스트 파일 만들고 나서 테스트 해보면 됩니다 
린트는 오류나면 
`npm install typescript@5.1.6 --save-dev`
`rm -rf node_modules
rm package-lock.json
npm install`
이렇게 하시면 됩니다 
프리티어는 뭐 VSC는 잘 모르겠소 
이모션은 App.tsx 이렇게 수정해서 테스트 해보세요 
```
/** @jsxImportSource @emotion/react */
import { useState } from 'react';
import reactLogo from './assets/react.svg';
import viteLogo from '/vite.svg';
import styled from '@emotion/styled';
import './App.css';
const Title = styled.h1`
color: blue;
`;
interface CardTextProps {
color?: …
```

[settings] eslint, emotion, husky, prettier 다 테스트, 수정 완료

---

package-lock.json
package.json
src/App.tsx
src/pages/Wage/Correction/Correction.tsx
src/pages/Wage/Correction/CorrectionDetail.tsx
tsconfig.app.json
tsconfig.node.json
vite.config.ts

path alias 설정 완료
tsconfig, vite.config 수정하고 App.tsx에 경로 @로 바꿧습니다
tsconfig, vite.config 수정하고 App.tsx에 경로 @로 바꿧습니다

[feature] path alias 설정 완료

---

package-lock.json
package.json
src/App.tsx
src/constants/colors.ts
src/styles/GlobalStyles.tsx
tsconfig.app.json

글로벌 스타일 세팅 완료
글로벌 스타일 세팅 완료
normalize.css를 설치해서 브라우저간의 차이점을 줄임 

[feature] 글로벌 스타일 세팅 완료

---

.gitignore
package-lock.json
package.json
src/firebaseConfig.ts

Firebase 초기 설정
Firebase Config 파일 생성 및 라이브러리 설치
Firebase 초기 설정을 진행했습니다.

[settings] Firebase 초기 설정

---

package-lock.json
package.json
src/App.tsx
src/components/Header.tsx
src/components/NavItem.tsx
src/components/RootLayout.tsx
src/interfaces/INavItemProps.ts
src/styles/GlobalStyles.tsx

lucide-react 패키지 추가 
헤더 퍼블리싱 + 라우터 연결 
컴포넌트 여러개로 분리 
App.js에서 연결
lucide-react 패키지 추가 
헤더 퍼블리싱 + 라우터 연결 
컴포넌트 여러개로 분리 
App.js에서 연결
lucide-react 패키지 추가 
헤더 퍼블리싱 + 라우터 연결 
컴포넌트 여러개로 분리 
App.js에서 연결

[feature] 헤더 컴포넌트 제작 완료 #27

---

src/components/Button.tsx
src/components/Input.tsx
src/constants/colors.ts
src/interfaces/button.d.ts
src/interfaces/input.d.ts

- Input, Button 컴포넌트 생성
- Input, Button 컴포넌트를 생성했습니다.
- 각 컴포넌트에서 필요한 interface 파일을 생성했습니다.
- Button 컴포넌트에서 hover 동작 시 필요한 색상을 colors 파일에 추가했습니다.
위와 같습니다.
각 컴포넌트 사용하는 방식이 직관적으로 이해하기 어려울 것 같아 예시 이미지를 첨부합니다.
필수 props 속성과 각 type을 잘 확인해서 사용해주세요!
-

[feat] Input, Button 컴포넌트 생성

---

package-lock.json
package.json
src/components/Modal.tsx
src/components/ScheduleModal.tsx
src/main.tsx
src/pages/Schedule/Schedule.tsx
src/stores/modalSlice.ts
src/stores/store.ts

모달 기본 레이아웃 설정 리덕스 툴킷 사용 
리덕스 툴킷 패키지 설치, 모달 레이아웃
리덕스 툴킷 패키지 설치, 모달 레이아웃 

[feature] 모달 기본 레이아웃 설정 리덕스 툴킷 사용 #19

---

src/layout/Content.tsx
src/layout/Layout.tsx
src/styles/GlobalStyles.tsx

**스크롤 이슈 수정 및 레이아웃 개선**
- `overflow: auto` 적용 시 스크롤바 직접 화면에 붙는 문제 수정
- `position` 속성 문제 해결을 위한 레이아웃 재조정
1. 전체적으로 position: absolute로 되어 있어서 하단메뉴가 안붙혀있는 문제가 발생함.
2. body에 `margin: 0 auto` 로 설정
1. `overflow: hidden`을 전체적으로 하면 스크롤이 잘되지 않는 이슈가 발생
2. Content 컴포넌트에  `overflow: auto` 제거, 글로벌 스타일 `overflow: hidden` 제거
콘텐츠가 넘칠 시 일부 섹션에 `overflow: hidden` 설정해야함

[fix] 스크롤 이슈 수정 및 레이아웃 개선

---

src/components/Calendar/CalendarBadge.tsx
src/components/Calendar/CalendarDates.tsx
src/components/Calendar/CalendarWeek.tsx
src/components/Calendar/CalenderContents.tsx
src/components/Calendar/ControlDate.tsx
src/components/IconButton.tsx

**캘린더, 아이콘 버튼 UI 수정]**
캘린더, 아이콘 버튼 UI 수정
0. 변경해야될 부분들이 조금씩 보여서 캘린더부터 pr올렸습니다. 컨플릭트 안나도록 추후 더 올릴 예정
1. 아이콘 버튼 크기는 키웠습니다.
2. 캘린더 폰트는 14px 설정(body가 이미 14px폰트라 fontSize.md 부분들은 지움)

[design] 캘린더, 아이콘 버튼 UI 수정

---

src/components/Calendar/mockdata.ts
src/components/ScheduleModal.tsx

모달 퍼블리싱 하고 기능 구현 약간 해봤습니다
모달 퍼블리싱 하고 기능 구현 약간 해봤습니다
추후에 모달 컴포넌트 분리하고 코드 전체적으로 정리할 예정입니다 
API랑 서버, 그리고 개인근무 일정표 페이지가 완성되야 모달도 어느정도 마무리가 가능합니다 
일단 중간점검인거 감안하고 봐주세요

[feature] 모달 기능 조금 구현 퍼플리싱 했음  #20

---

src/components/Home/SummaryInfoCard.tsx
src/pages/Home.tsx

홈페이지 UI 퍼블리싱 작업
1. 홈페이지 퍼블리싱
2. 현재 월 표시
3. 공식스케줄 근무시간 표시(목데이터)
4. 공식스케줄 예상 급여액 표시(목데이터)

[feature] 홈페이지 UI 퍼블리싱 작업

---

src/constants/font.ts
src/pages/Wage/WageCheck/WageCheckDetail.tsx

급여 상세내역 UI
급여 상세내역 Design
급여 상세내역 UI

[Design]급여 상세내역 UI

---

package.json

package.json 중복 요소 삭제
package.json 중복 요소 삭제
리엑트 라우트 돔 두개 있었어요
package.json 중복 요소 삭제

[bug] package.json 중복 요소 삭제

---

src/components/Wage/ControlMonth.tsx
src/components/Wage/WageTab.tsx
src/components/Wage/WorkHistory.tsx
src/constants/font.ts
src/layout/Header.tsx
src/layout/Layout.tsx
src/layout/Menu/Menu.tsx
src/layout/Menu/MenuItem.tsx
src/pages/Wage/Wage.tsx
src/pages/Wage/WageCheck/WageCheck.tsx
src/pages/Wage/WageCheck/WageCheckDetail.tsx
src/styles/GlobalStyles.tsx

**layout컴포넌트 css, 급여확인 css 수정**
layout컴포넌트 css, 급여확인 css 수정
좀 많이 수정했습니다...

[Design] layout컴포넌트 css, 급여확인 css 수정

---

.eslintrc.cjs
src/components/Profile/ProfileMenu.tsx
src/components/Profile/UserProfile.tsx
src/pages/Profile.tsx

프로필 페이지 디자인 
프로필페이지 디자인작업입니다
프로필 페이지 디자인

[Design] 프로필페이지 디자인 

---

src/App.tsx
src/components/Profile/ProfileMenu.tsx
src/pages/UnderConstruction.tsx

준비중 페이지 UI 및 라우팅 연결
프로필 페이지의 각 메뉴들을 클릭 시 준비중 페이지로 라우팅
준비중 페이지 UI 및 라우팅 연결

[Feat]프로필페이지 메뉴들 라우팅

---

package-lock.json
src/api/auth/checkAuth.ts
src/api/common/getDocsByUserId.ts
src/api/common/getUserId.ts

- Firebase API 공통 로직 구현
- API에서 사용되는 공통적인 로직을 추가했습니다.
위와 같습니다.
- 
-

[feature] Firebase API 공통 로직 구현

---

src/api/schedule/getOfficialSchedule.ts
src/api/work/getOfficialWage.ts
src/api/work/getPersonalWage.ts

Firestore 컬렉션 데이터, API 일부 수정
- Firestore에 근무 일정 관련 데이터 타입을 string에서 array 형식으로 변경 적용했습니다.
- 데이터 타입이 바뀜에 따라 기존에 작성된 API 로직을 수정했습니다.
위와 같습니다.
- 
-

[bug] Firestore 컬렉션 데이터, API 일부 수정

---

package-lock.json
src/components/SheduleModal/ScheduleModal.tsx
src/components/SheduleModal/ScheduleModalForm.tsx
src/components/common/Dropdown.tsx
src/components/common/Input.tsx
src/data/mockdata.ts

모달 폼에 드롭다운 컴포넌트를 만들었습니다
모달 폼에 드롭다운 컴포넌트를 만들었습니다
주요 변경 사항을 요약해 주세요.
오늘 만난 말 친구

[feature] 모달 폼에 드롭다운 컴포넌트를 만들었습니다

---

src/api/work/getOfficialWage.ts
src/components/Profile/UserProfile.tsx
src/components/Wage/ControlMonth.tsx
src/components/Wage/WorkHistory.tsx
src/components/common/Button/IconButton.tsx
src/pages/Profile.tsx
src/pages/Wage/WageCheck/WageCheck.tsx

프로필페이지, 급여 페이지 api 연동
프로필페이지, 급여 페이지 api 연동하였습니다
프로필페이지, 급여 페이지 api 연동

[Feat] 프로필페이지, 급여 페이지 api 연동

---

src/api/auth/logout.ts
src/components/Profile/ProfileMenu.tsx
src/components/common/Button/UnderlineTextButton.tsx
src/components/common/Input.tsx
src/hooks/useLogin.ts
src/pages/Login.tsx
src/pages/Profile.tsx

로그인 기능 추가 구현
- 로그인 페이지에서 아이디와 비밀번호를 모두 입력해야만 로그인 버튼이 활성화되도록 했습니다.
- 로그인 페이지에서 Enter 키를 눌러 로그인할 수 있도록 구현했습니다.
- 로그아웃에 사용될 UnderlineTextButton 컴포넌트를 구현했습니다.
- 프로필 페이지에 로그아웃 기능을 구현했습니다.
- 로그인 페이지 파일에서 로직 영역 코드를 useLogin Custom Hook으로 분리했습니다.
위와 같습니다.
-

[feature] 로그인 관련 기능 추가 구현

---

src/components/common/Calendar/CalendarDates.tsx
src/components/common/Calendar/CalendarWeek.tsx
src/components/common/Calendar/CalenderContents.tsx
src/constants/colors.ts
src/hooks/useSchedules.ts
src/utils/dateUtils.tsx

캘린더 디자인 변경하기 
- 토요일:파란색, 일요일:빨간색으로 표시하기
- 이전달 마지막 일, 다음달 처음 일들은 상세페이지 이동을 막고, 클릭 안되도록 처리, 회색 글씨 처리

[design] 캘린더 디자인 변경하기  

---

src/components/SheduleModal/ScheduleModal.tsx
src/pages/Schedule/ScheduleDetail.tsx
src/stores/scheduleSlice.ts
src/stores/store.ts

모달 리덕스 연결 완료 했습니다 !!
모달 리덕스 연결 완료 했습니다 !!
모달 리덕스 연결 완료 했습니다 !!

[feature] 모달 리덕스 연결 완료 했습니다 !!

---

src/App.tsx

- 라우팅 방식 개선 작업
- App.tsx 파일의 라우팅 처리 방식을 중간 점검 피드백을 반영하여 개선했습니다.
- createBrowserRouter, RouterProvider를 이용한 라우팅 처리 방식에서 BrowserRouter, Routes, Route를 이용한 컴포넌트 라우팅 방식으로 변경했습니다.
- 
-

[feature] 라우팅 방식 개선

---

src/pages/Profile.tsx
src/pages/Schedule/ScheduleDetail.tsx

로딩 기능 구현 PR 과정에서 발생한 conflict 미반영 사항 수정
- 로딩 기능 구현 PR 과정에서 발생한 conflict 미반영 사항을 수정했습니다.
위와 같습니다.
- 
-

[bug] 로딩 기능 구현 PR 과정에서 발생한 conflict 미반영 사항 수정

---

src/api/work/createCorrection.ts
src/api/work/getCorrection.ts
src/components/SheduleModal/ScheduleModalForm.tsx
src/components/Wage/CorrectionTable.tsx
src/components/common/Dropdown.tsx
src/components/common/Input.tsx
src/components/common/Select.tsx
src/constants/options.ts
src/pages/Wage/Correction/Correction.tsx
src/pages/Wage/Correction/CorrectionRequest.tsx
src/utils/labelUtils.ts

**정정신청하기 페이지 퍼블리싱 및 신청하기 기능구현**
- 정정신청 하기 기능 
- 정정신청 하기(빈값으로 값을 넘겨줄때 focus 기능 )
- 정정 신청 필터링 기능(전체 추가)
- useRef를 사용하여 input, dropdown, select 컴포넌트에 포커스 기능을 추가했습니다.
- 현재 사용 중인 드롭다운은 한 번에 하나의 상태값만 처리할 수 있습니다. 개발 중인 기능은 다양한 데이터 타입을 필요로 하므로, 새로운 select 컴포넌트로 추가했습니다.
- 이 변경으로 인해 드롭다운이 포함된 모달도 함께 수정했습니다.
|                                                   정정 신청 필터링 기능                                                 |                                                    정정신청 하기 기능                                                  |                                                   정정신청 하기 - 빈값으로 값을 넘겨줄때 focus 기능                                                  |                                
| :--------------------------------------------------------------------------------------------------------- …

[feat] 정정신청하기 페이지 퍼블리싱 및 신청하기 기능구현

---

README.md

**[작업 내용을 간략히 적어주세요]**
- 멤버들 깃허브 링크 연결 및 역할 명시
- 프로젝트 기간 작성
- 기술스택 뱃지 달기(아래 링크 추가)
- 우리가 프로젝트한 issue(open/close), pr(open/close) 갯수 뱃지 달기(아래 링크 추가)
- 실행방법 작성
- 기능명세서 작성(깃허브 위키)
- ERD 구조 추가
영상은 추후 첨부 예정

[feature] 리드미 파일 작성

---

src/components/Loading.tsx

로딩창 디자인 수정
수정한 내용이나 추가한 기능에 대해 자세히 설명해 주세요.
로딩창 디자인 수정

[Design]로딩창 디자인 수정

---

src/components/SheduleModal/ScheduleModal.tsx
src/pages/Schedule/ScheduleDetail.tsx

이제 기존에 일정이 없어도 일정 추가가 제대로 진행됩니다
이제 기존에 일정이 없어도 일정 추가가 제대로 진행됩니다
이제 기존에 일정이 없어도 일정 추가가 제대로 진행됩니다

[bug] 이제 기존에 일정이 없어도 일정 추가가 제대로 진행됩니다

---

src/hooks/useWageCheck.ts
src/pages/Wage/WageCheck/WageCheck.tsx

useWageCheck 커스텀훅 분리
수정한 내용이나 추가한 기능에 대해 자세히 설명해 주세요.
useWageCheck 커스텀훅 분리

[fix]useWageCheck 커스텀훅 분리

---

package-lock.json
src/components/Loading/Loading.tsx

**오리파일 경로찾기 및 package-lock.json 업데이트**
오리파일 경로찾기 및 package-lock.json 업데이트
오리파일 경로찾기 및 package-lock.json 업데이트

[bug] 오리파일 경로찾기 및 package-lock.json 업데이트

---

src/components/Wage/ControlMonth.tsx
src/components/Wage/CorrectionTable.tsx
src/components/Wage/SalaryCard.tsx
src/components/Wage/WageTab.tsx
src/components/Wage/WorkHistory.tsx
src/components/common/Button/IconButton.tsx
src/components/common/Dropdown.tsx
src/constants/options.ts
src/layout/Layout.tsx
src/pages/Wage/Correction/Correction.tsx
src/pages/Wage/WageCheck/WageCheck.tsx
src/pages/Wage/WageCheck/WageCheckDetail.tsx

**급여 내역, 정정 신청 페이지 css 최종 수정**
급여 내역, 정정 신청 페이지 css 최종 수정
급여 내역, 정정 신청 페이지 css 최종 수정
파베가 죽은 바람에... 캡쳐가 없음...

[design] 급여 내역, 정정 신청 페이지 css 최종 수정

---

src/hooks/useWageCheck.ts

**[작업 내용을 간략히 적어주세요]**
api 데이터를 반환할 뿐인 함수를 useQuery에 바로 api 연결
api 데이터를 반환할 뿐인 함수를 useQuery에 바로 api 연결

[Refactor]멘토님 피드백 반영하여 useWageCheck 수정

---

src/components/SheduleModal/ScheduleModal.tsx
src/components/SheduleModal/ScheduleModalFooter.tsx
src/utils/dateUtils.ts

모달 피드백 전부 적용했습니다
모달 피드백 전부 적용했습니다
모달 피드백 전부 적용했습니다
코드리뷰 PR 참조바람 

[feature] 모달 피드백 전부 적용했습니다
